name: Gerar Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar ambiente
        uses: actions/checkout@v2

      - name: Construir APK
        run: sh gradlew assembleRelease

      - name: Publicar release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v2.0.0
          release_name: Release v2.0.0
          draft: false
          prerelease: false
          #files: |
          #  app/build/outputs/apk/release